services:
  numerology-pro:
    build:
      context: .
      dockerfile: Dockerfile
    image: numerology-pro:latest
    container_name: numerology-pro
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"http=require('http');http.get('http://localhost:'+process.env.PORT, r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 30s
      timeout: 5s
      retries: 5
